### ISSUE TITLE
Que es el "Scrum"?

### ISSUE THREAD

**Issue by yerlo** [GRUPO-4-ISPC/PROG.group4-ispc2#2]
Documentar respuesta en el archivo de texto "ConceptosScrum.md"

**Comment by CariViShine** [comment]
Definición de Scrum
Scrum es un marco de trabajo liviano que ayuda a las personas, equipos y organizaciones a generar valor
a través de soluciones adaptativas para problemas complejos.
  
En pocas palabras, Scrum requiere un Scrum Master para fomentar un entorno donde:
  
1. Un Product Owner ordena el trabajo de un problema complejo en un Product Backlog.
2. El Scrum Team convierte una selección del trabajo en un Increment de valor durante un Sprint.
3. El Scrum Team y sus interesados inspeccionan los resultados y se adaptan para el próximo
Sprint.
4. Repita
  
Scrum es simple. Pruébelo como está y determine si su filosofía, teoría y estructura ayudan a lograr
objetivos y crear valor. El marco de trabajo Scrum es incompleto de manera intencional, solo define las
partes necesarias para implementar la teoría de Scrum. Scrum se basa en la inteligencia colectiva de las
personas que lo utilizan. En lugar de proporcionar a las personas instrucciones detalladas, las reglas de
Scrum guían sus relaciones e interacciones.
En este marco de trabajo pueden emplearse varios procesos, técnicas y métodos. Scrum envuelve las
prácticas existentes o las hace innecesarias. Scrum hace visible la eficacia relativa de las técnicas
actuales de gestión, entorno y trabajo, de modo que se puedan realizar mejoras.
